### ISSUE TITLE
bad_alloc

### ISSUE THREAD

**Issue by TracyBallinger** [seqan/anise_basil#5]
Hello, I'm trying to use anise_basil to assemble some breakpoints around a duplication.  I generated a basil.vcf file and am trying to run the anise step where I get the following error after it assembles 8/123 of the sites: 

00:11/00:02:49]terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

When I run it with the -v option, I get this error description: 
Building Consensus...
Building alignment graph
  # fragments: 0
  # seqs: 295
progressive alignment...
build AG..
AG
  numVertices = 295
  numEdges = 0
  componentLength.size() = 295
  numComponents = 295
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

I'm running it on a small (6 Mb) section of chr2, and the basil step detects 124 potential breakpoints, all of which I use in the anise assembly.  
The machine I'm running it on has 16G, and anise seems to be using only a little over 1G, so it doesn't seem to be running out of memory.  

Please let me know if you would like me to send my input files.  

Thanks!

**Comment by holtgrewe** [comment]
I think this was caused by using the `-M` flag to `bwa`.

If the problem still persists, please reopen.
