### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by eseiler** [seqan/anise_basil#6]
I tried to install anise_basil according to the readme, but the make command fails due to seqan files not being found.
Here is a log file: [build_anise_basil.txt](https://github.com/seqan/anise_basil/files/541674/build_anise_basil.txt)

**Comment by holtgrewe** [comment]
Have you executed the line `git submodule update --recursive`?

**Comment by eseiler** [comment]
Yes, I did.
These are the command I executed:

git clone https://github.com/seqan/anise_basil.git
cd anise_basil
git checkout develop
git submodule init
git submodule update --recursive
cd build
cmake ..
make -j 4 anise basil

And the error that occurs with different files when running 'make -j4 anise basil' is:
/home/RKID1/seilere/hgt_tools/tools/anise_basil/src/shared/progress_indicator.cpp:38:33: fatal error: seqan/misc/terminal.h: Datei oder Verzeichnis nicht gefunden
 #include <seqan/misc/terminal.h>

**Comment by holtgrewe** [comment]
Do you have an old version of seqan somewhere? It appears that it finds seqan v1.4.1 for you but I would expect it to find seqan v2.0.0...

**Comment by ktrappe** [comment]
Yes, we have an old seqan version globally installed, and we (probably) can't change that atm (new server setup is coming end of the year). We use local checkouts for the other apps.

**Comment by holtgrewe** [comment]
@eseiler show me the result of `export | grep -i seqan`

**Comment by eseiler** [comment]
There is no output.

**Comment by holtgrewe** [comment]
Try removing everything within the build directory. Then `export SEQAN_INCLUDE_PATH=../ext/seqan/include` before calling cmake.

**Comment by ktrappe** [comment]
(sorry for taking over again)
`export SEQAN_INCLUDE_PATH=../ext/seqan/include` gives the same result/errors

**Comment by holtgrewe** [comment]
OK, I don't have time to look into this. The build system picks up the globally installed one instead of the local one.

**Comment by ktrappe** [comment]
I built it on the FU cluster and both builds seem to work on our server, so we found a circumvention. Thanks for now @holtgrewe.
