### ISSUE TITLE
anise Segmentation fault

### ISSUE THREAD

**Issue by hepcat72** [seqan/anise_basil#7]
Basil found a very good candidate for our anticipated 2kb insert, but when I ran anice to assemble it, I get a segfault fairly quickly:

```
./anise_basil/build/bin/anise -ir Pseudomonas_aeruginosa_UCBPP-PA14_109.fa -im PA14_1_pe_trimmed.bam -iv PA14_1_pe_trimmed.basil.filtered.vcf -of PA14_1_pe_trimmed.basil.filtered.anise.vcf.fa
Parsing command line...
Loading global state...
Checking input...
Estimating library size...
  estimation complete |################################################| 100000/100000 [00:00:00/00:00:00]
  library size: median=344, stdDev=97.9034
Perform preparation step...
  extracted sites |                                                | 0/1 [00:00:06/00:00:00]Segmentation fault
```

I am using an index created by samtools:

`samtools faidx Pseudomonas_aeruginosa_UCBPP-PA14_109.fa`

Could that be the issue?

Thanks,
Rob

**Comment by holtgrewe** [comment]
Hi

It's very hard to say what's going on without the data. Are you able to share the region around the insert? I could have a look (manuel.holtgrewe at bihealth.de).

Cheers

**Comment by hepcat72** [comment]
I will consult the person who owns the data and get back to you.

Rob

Robert William Leach
137A Carl C. Icahn Lab
Lewis-Sigler Institute for Integrative Genomics
Princeton University
Princeton, NJ 08544

**Comment by hepcat72** [comment]
Incidentally, I was able to find the complete insert in one of the contigs generated from a different assembler.

Rob

Robert William Leach
137A Carl C. Icahn Lab
Lewis-Sigler Institute for Integrative Genomics
Princeton University
Princeton, NJ 08544

**Comment by hepcat72** [comment]
I emailed you the files via mailbigfile.com.  Let me know if it comes through OK.

**Comment by hepcat72** [comment]
BTW, I discovered that I was using the wrong type of index in the data I sent you.  However, after fixing that, it still segfaults.  I also tried re-sorting my bam just in case, same result.  I think that covers all my possible mistakes, but I could be wrong...

**Comment by holtgrewe** [comment]
Thank you for all of this information. I hope I can make some free time to look into this soon.

**Comment by hepcat72** [comment]
I think the mailbigfile.com link only lasts a week before it's deleted, so just make sure you download it before then.

**Comment by holtgrewe** [comment]
OK, could you try to run from the master branch?

Apparently, this is 4 commits ahead of the develop branch (which I give as the branch to use in the README for reasons that are beyond me right now). For me, the master branch runs through.

I'll update the README right away.

**Comment by rrahn** [comment]
What's the status of this issue?

**Comment by lsmainzer** [comment]
Hello. I am getting the same error on my data, in some chromosomes, but not all. Would you be willing to help sort it out?

**Comment by holtgrewe** [comment]
@lsmainzer yes, if you can make a subset of your data available to me where it crashes

**Comment by hepcat72** [comment]
I recall I had just used a different assembler and didn't have time to dig into this issue.  Sorry about that.

**Comment by lsmainzer** [comment]
Hello.  Thank you very much for quick response! We may not be able to share the data due to medical privacy issues. However, we may be able to reproduce the problem on an open dataset. We will pursue both avenues and will post shortly. Thanks!

**Comment by lsmainzer** [comment]
Okay, we got permission to share the subset of the data. What is the best way to do that privately, @holtgrewe ?

**Comment by holtgrewe** [comment]
@lsmainzer please contact me via email (you can find it on my profile https://github.com/holtgrewe)
